services:
  t3-site:
    build: ./t3-site
    expose:
      - "80"

  t4-site:
    build: ./t4-site
    expose:
      - "80"

  t4-site-content:
    build: ./t4-site-content
    expose:
      - "80"

  node-red:
    build: ./nodered
    container_name: node-red
    ports:
      - "1880:1880"

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${SSL_CERT_PATH}:/certs/cert.pem:ro
      - ${SSL_KEY_PATH}:/certs/key.pem:ro
      - ${ACME_WEBROOT}:/usr/share/nginx/html:ro
      - ./nginx/logs/:/var/log/nginx/
    depends_on:
      - t3-site
      - t4-site
      - node-red
      - t4-site-content
