version: '3'

services:
  react-app:
    build: ./frontend
    container_name: react-app
    expose:
      - "80"

  node-red:
    build: ./nodered
    container_name: node-red
    ports:
      - "1880:1880"

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - react-app
      - node-red
